spring:
  datasource:
    username: ziyang
    password: '{cipher}AQCMlgS2G6FG7U7IbGlLmWQcySXsjXKfyzGPHribHSQQWKFb9sTS6Qo6jIdYHG2uoF3MBjpTpHoK+GUCwxx9YQurrshC690g1le9P6Ixucrbh1ns+/gjnGPbvdDuSJEE0PtZ8njePr3tCFgGqT+62D1uFjB2MGHCiPpVIa9dN6qr7pK7uqwuJr9eEjDJ1quUorsdalSATIWtr0rIUmqD9Byc9TChDpFI4GKXEgZag6Y9yfhi8+rRjFWUx4pRB4EYYs80T018gT6QJNfwj1XQUc2jEEg/5JeX48kUopE99wU9NMVfyj0QMPkw8I4kltFVqPgjMmom3YpEv5N/Av5ozE6kOoTSalY7nJWk3OoaaOo3JaYY8B3nmKmQJNsabLJgq5w='
