spring:
  datasource:
    username: ziyang
    password: '{cipher}UigWnrdfrE1jhdI6+9w9r1PHY7Xjp7xbdImiPY6gjA+ko4ol4jPF8Wk+14UwDdVepcfIcJyDHfahHHF4M1YmfCGlMGcuMylssL07JVO3J9H1Tnxo5nFuziZQOQYsXG+hGSGsgFc/OGXf5w64OfANVhsK3tUksLvBkSAeoR5DC91w8pMLXcdsXw9eAxrvtGgJxBMRkWEpqhTDM9uYanXlmANQ4ynWJzdJesIlx1I9VHQu2IJvSrLJ0GNZglTDojZtGvh8IwUiIM+1MnmZgPmdQFwZPTyX/g3j8oCtIjOkVQaJKA5ajciyb2x3hWU1UL4BW9hC3M1K4FAs5cfO1nvAK6AVxhklxWxWu3M6T6kyVOAvkoTPFw8RwgU='
